const ProductConstants = {
	GET_PRODUCTS_REQUEST: 'GET_PRODUCTS_REQUEST',
	GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',

	ADD_TO_CART_REQUEST: 'ADD_TO_CART_REQUEST',
	ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',

	REMOVE_FROM_CART_REQUEST: 'REMOVE_FROM_CART_REQUEST',
	REMOVE_FORM_CART_SUCCESS: 'REMOVE_FORM_CART_SUCCESS'
};

export default ProductConstants;